### ISSUE TITLE
[FEATURE] Auto run when a instance is already running 

### ISSUE THREAD

**Issue by NagisaVon** [Luke-zhang-04/processing-vscode#14]
Thanks for this great plug-in!

A little issue I have is that processing.Run won't run an instance that is already running, it would be really helpful if the plugin could kill the previous running instance and rerun, kind of like pressing ctrl-c in the terminal for us.

**Comment by Luke-zhang-04** [comment]
Good idea! I'll get it done over the weekend.

**Comment by NagisaVon** [comment]
Thanks!!

**Comment by Luke-zhang-04** [comment]
Ok so after some research, I don't know if there's a good way to do this. I tried looking at the Python extension's run button, and it has the same behaviour. I'll try to see if there's another way but otherwise I don't think this will work unfortunately.

**Comment by Luke-zhang-04** [comment]
This feature will be implemented with the next release (2.5.0). You can set `processing.shouldSendSigint` to `true` for this to work. It's turned off by default as it could potentially cause cross-platform issues.
