### ISSUE TITLE
[BUG] Run doesn't work with spaced paths

### ISSUE THREAD

**Issue by qizhu-work** [Luke-zhang-04/processing-vscode#2]
Terminal output when trying to run the sketch in a path with spaces

PS D:\Google Drive\\...\sketch --run
d:\Google does not exist.

**Comment by Luke-zhang-04** [comment]
Thought this was fixed with #1. I'll take a look again

**Comment by Luke-zhang-04** [comment]
So apparently I'm completely stupid and didn't publish the new releases since I thought I had auto deploys on. Latest version should fix the issue.
