### ISSUE TITLE
problem with tasks.json and processing.path

### ISSUE THREAD

**Issue by knupel** [Luke-zhang-04/processing-vscode#20]
Hello,
I try to use your Processing impl for VS code, but that's don't work because there is a problem with `config:processing.path` in the `tasks.json` that's work fine with the Tobiah Zarlez version.
In your comment in VS code I don't find anyhing about the  tasks.json. so I don't know what I must do to solve this problem.

```
Variable ${config:processing.path} can not be resolved because setting 'processing.path' not found.
```

I'm on Processing 4.02b with an Mac OS Monterey.

Thanks for your work

**Comment by Luke-zhang-04** [comment]
I renamed `processing.path` to `processing.processingPath`. Try changing that and let me know if it works.

Alternatively, there's also the run button. You can try binding a key to that command if you want, but the task file should work either way.

**Comment by knupel** [comment]
Perfect, that's work like a charm. But maybe add your `tasks.json` in your `guide` in VS Code or change this path to the original one. It's a little disturbing to have this trouble... I think you can lost user just for that !

**Comment by Luke-zhang-04** [comment]
Ok, thanks for the feedback!
