### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by knupel** [Luke-zhang-04/processing-vscode#26]
Hello,

I'm not sure it's a bug, but now when I hit "CMD + SHIFT + B" my sketch failed with this message

```
 *  Terminal will be reused by tasks, press any key to close it. 

zsh:1: command not found: processing-java

 *  The terminal process "/bin/zsh '-c', 'processing-java --force --sketch=/Users/stanislasmarcais/EN_COURS/CODE/github/PROJET/Mosaique --output=/Users/stanislasmarcais/EN_COURS/CODE/github/PROJET/Mosaique/out --run'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

I don't understand this message, yesterday that's command work like a charm... and today no. Maybe I changed something in my configuration. But when I pass by the `command palette` and use `Processing: Run Open Processing Java Project` that's work. It's very weird.
So if you have an idea of what happen, that's can be great.

**Comment by Luke-zhang-04** [comment]
Is processing-java in your path? It's saying you processing-java isn't a known command. Did you update processing to 4.0 recently? If that's the problem, I'm working on that soon.

**Comment by hjlinq** [comment]
I'm getting the same error on Windows
![image](https://user-images.githubusercontent.com/68657588/215906994-1dfca070-7745-4564-abb8-57ca532cc72c.png)

**Comment by Luke-zhang-04** [comment]
Is `processing-java` in your path? What happens when you run `processing-java` in the command line?

**Comment by hjlinq** [comment]
No it wasn't, I added it and it works now. 

I just brought it up since you said you were going to work on it earlier.

**Comment by Luke-zhang-04** [comment]
Ok, good to hear

**Comment by Luke-zhang-04** [comment]
Closing unless problem persists
