### ISSUE TITLE
[FEATURE] Adding support for different "Modes" [Python, Android, P5.js]

### ISSUE THREAD

**Issue by b-mq** [Luke-zhang-04/processing-vscode#5]
First thank you for creating this extension!

Currently you can only run a Processing sketch which is written in Java (.pde)
Support for different Processing "Modes" like Python (.pyde), Android, P5.js would be nice 
It would be great if one could make it work with [Processing Python Mode](https://py.processing.org/).

Here's a possible solution, how to run [Processing in Python mode inside VSCode](https://discourse.processing.org/t/tutorial-running-python-mode-in-vscode/7716)

_Processing Modes:_
![image](https://user-images.githubusercontent.com/3727554/118827598-d1505f80-b8bc-11eb-99c4-7e4b48cba238.png)

**Comment by Luke-zhang-04** [comment]
Thanks for the suggestion! I'm a bit busy right now, but I'll get on it when I have time.

I can definitely get Python mode to work. p5js looks like it runs in the browser, so I'm not sure if adding that would work, but I'll take a look. Processing with Android seems like something else, so I probably won't be implementing that.

**Comment by b-mq** [comment]
Thanks!
Can't wait to use Processing.py inside of VSCode
